// ===============================
// SEED SCRIPT - Import products to MongoDB
// ===============================

require("dotenv").config();
const mongoose = require("mongoose");
const Product = require("./models/Product");

const products = [

    // VEGETABLES
    { name: "Fresh Tomato", price: 60, unit: "kg", category: "Vegetables", emoji: "🍅", gradient: "linear-gradient(135deg, #ff6b6b, #ee5a24)", description: "Fresh farm-picked tomatoes, juicy and ripe. Perfect for curries, salads, chutneys and sauces.", nutrition: "Rich in Vitamin C, Potassium, Folate and Vitamin K. Low in calories.", tips: "Store at room temperature until ripe. Refrigerate after ripening to last longer.", origin: "Nashik, Maharashtra", stock: 50 },
    { name: "Potato", price: 1, unit: "kg", category: "Vegetables", emoji: "🥔", gradient: "linear-gradient(135deg, #d4a574, #c0956c)", description: "Premium quality potatoes, perfect for boiling, frying, baking or making delicious aloo dishes.", nutrition: "Good source of Carbohydrates, Vitamin B6, Potassium and Fiber.", tips: "Store in a cool, dark and dry place. Keep away from onions as they release gases.", origin: "Agra, UP", stock: 100 },
    { name: "Onion", price: 60, unit: "kg", category: "Vegetables", emoji: "🧅", gradient: "linear-gradient(135deg, #f0c27f, #d4a056)", description: "Fresh onions with strong flavor. Essential for Indian cooking, salads and pickles.", nutrition: "Rich in Vitamin C, B6, Potassium and antioxidants like Quercetin.", tips: "Store in a cool, dry and ventilated place. Can last several weeks.", origin: "Nashik, Maharashtra", stock: 100 },
    { name: "Carrot", price: 40, unit: "kg", category: "Vegetables", emoji: "🥕", gradient: "linear-gradient(135deg, #ff9a44, #fc6076)", description: "Sweet and crunchy carrots, ideal for salads, juices, halwa and curries.", nutrition: "Excellent source of Beta-carotene, Vitamin A, Fiber and Potassium.", tips: "Remove green tops before storing. Keep in refrigerator in a plastic bag.", origin: "Bangalore, Karnataka", stock: 40 },
    { name: "Cauliflower", price: 100, unit: "kg", category: "Vegetables", emoji: "🥦", gradient: "linear-gradient(135deg, #a8e063, #56ab2f)", description: "Fresh white cauliflower with tight florets. Great for gobi manchurian, paratha and curry.", nutrition: "High in Vitamin C, Vitamin K, Fiber and Folate.", tips: "Store unwashed in refrigerator. Use within a week for best freshness.", origin: "Pune, Maharashtra", stock: 30 },
    { name: "Cabbage", price: 40, unit: "kg", category: "Vegetables", emoji: "🥬", gradient: "linear-gradient(135deg, #56ab2f, #a8e063)", description: "Crisp green cabbage, perfect for salads, sabzi, chowmein and coleslaw.", nutrition: "Rich in Vitamin C, Vitamin K, Fiber and antioxidants.", tips: "Store in refrigerator crisper drawer. Stays fresh for up to 2 weeks.", origin: "Indore, MP", stock: 40 },
    { name: "Capsicum", price: 80, unit: "kg", category: "Vegetables", emoji: "🫑", gradient: "linear-gradient(135deg, #11998e, #38ef7d)", description: "Colorful capsicum with sweet flavor. Perfect for stir-fry, pizza, salads and stuffed dishes.", nutrition: "Excellent source of Vitamin C, Vitamin A and antioxidants.", tips: "Store in refrigerator crisper. Use within 5 days for best taste.", origin: "Hyderabad, Telangana", stock: 35 },
    { name: "Green Peas", price: 200, unit: "kg", category: "Vegetables", emoji: "🫛", gradient: "linear-gradient(135deg, #56ab2f, #2d8f2d)", description: "Fresh sweet green peas, perfect for matar paneer, pulao, samosa filling and snacks.", nutrition: "High in Protein, Fiber, Vitamin K and antioxidants.", tips: "Shell and store in airtight container. Refrigerate and use within 2-3 days.", origin: "Satara, Maharashtra", stock: 30 },
    { name: "Cucumber", price: 30, unit: "kg", category: "Vegetables", emoji: "🥒", gradient: "linear-gradient(135deg, #56ab2f, #11998e)", description: "Cool and refreshing cucumber, ideal for salads, raita, sandwiches and detox water.", nutrition: "96% water content. Good source of Vitamin K and Potassium.", tips: "Store in refrigerator. Wrap in paper towel to absorb excess moisture.", origin: "Rajasthan", stock: 45 },
    { name: "Spinach (Palak)", price: 30, unit: "kg", category: "Vegetables", emoji: "🥬", gradient: "linear-gradient(135deg, #11998e, #56ab2f)", description: "Fresh green spinach leaves. Perfect for palak paneer, soup, paratha and smoothies.", nutrition: "Rich in Iron, Vitamin A, Vitamin C, Calcium and Folate.", tips: "Wash thoroughly before use. Store wrapped in damp paper towel in fridge.", origin: "Pune, Maharashtra", stock: 40 },
    { name: "Brinjal", price: 40, unit: "kg", category: "Vegetables", emoji: "🍆", gradient: "linear-gradient(135deg, #7b4397, #dc2430)", description: "Fresh purple brinjal, perfect for baingan bharta, curries, grill and curd brinjal.", nutrition: "Low in calories. Rich in Fiber, Vitamin B1 and antioxidants.", tips: "Store at room temperature. Use within 2-3 days. Do not cut until ready to use.", origin: "Varanasi, UP", stock: 35 },
    { name: "Bottle Gourd (Lauki)", price: 30, unit: "kg", category: "Vegetables", emoji: "🥒", gradient: "linear-gradient(135deg, #a8e063, #11998e)", description: "Fresh bottle gourd, light and healthy. Great for dal, sabzi, juice and kofta.", nutrition: "Low in calories. High in water content, Vitamin C and Zinc.", tips: "Store in refrigerator. Cut pieces can be wrapped and refrigerated for 2 days.", origin: "Lucknow, UP", stock: 30 },
    { name: "Bitter Gourd (Karela)", price: 40, unit: "kg", category: "Vegetables", emoji: "🥬", gradient: "linear-gradient(135deg, #56ab2f, #2d8f2d)", description: "Fresh bitter gourd with natural bitterness. Great for karela sabzi, chips and juice.", nutrition: "Rich in Vitamin C, Iron, Potassium and insulin-like compounds.", tips: "Soak in salt water for 30 minutes to reduce bitterness before cooking.", origin: "Indore, MP", stock: 25 },
    { name: "Radish (Mooli)", price: 30, unit: "kg", category: "Vegetables", emoji: "🥬", gradient: "linear-gradient(135deg, #f5f5f5, #dc2430)", description: "Crisp white radish, ideal for paratha, salad, pickle and mooli ki sabzi.", nutrition: "Low in calories. Rich in Vitamin C, Fiber and Potassium.", tips: "Remove greens before storing. Keep in refrigerator for up to a week.", origin: "Delhi NCR", stock: 30 },
    { name: "Beetroot", price: 40, unit: "kg", category: "Vegetables", emoji: "🫒", gradient: "linear-gradient(135deg, #8b0000, #dc143c)", description: "Deep red beetroot, perfect for salad, juice, halwa and healthy cooking.", nutrition: "Rich in Iron, Folate, Manganese and nitrates for blood flow.", tips: "Store in refrigerator. Wrap individually in foil to keep fresh longer.", origin: "Pune, Maharashtra", stock: 30 },
    { name: "Garlic", price: 200, unit: "kg", category: "Vegetables", emoji: "🧄", gradient: "linear-gradient(135deg, #f5f5dc, #d4a574)", description: "Fresh aromatic garlic cloves, essential for Indian and global cuisines.", nutrition: "Contains Allicin. Rich in Manganese, Vitamin B6 and Vitamin C.", tips: "Store in a cool, dry place with good ventilation. Do not refrigerate.", origin: "Guntur, Andhra Pradesh", stock: 20 },
    { name: "Ginger", price: 150, unit: "kg", category: "Vegetables", emoji: "🫚", gradient: "linear-gradient(135deg, #d4a574, #c0956c)", description: "Fresh ginger root with warm, spicy flavor. Essential for chai, curries and remedies.", nutrition: "Contains Gingerol. Helps with digestion, nausea and inflammation.", tips: "Store in refrigerator in paper bag. Can also be frozen for longer storage.", origin: "Meghalaya", stock: 25 },
    { name: "Green Chilli", price: 80, unit: "kg", category: "Vegetables", emoji: "🌶️", gradient: "linear-gradient(135deg, #56ab2f, #ff6347)", description: "Fresh hot green chillies for that perfect spicy kick in every dish.", nutrition: "Rich in Capsaicin, Vitamin C and Vitamin A. Boosts metabolism.", tips: "Store in refrigerator. Remove stems before storing to last longer.", origin: "Guntur, Andhra Pradesh", stock: 30 },
    { name: "Coriander (Dhaniya)", price: 50, unit: "kg", category: "Vegetables", emoji: "🌿", gradient: "linear-gradient(135deg, #56ab2f, #a8e063)", description: "Fresh coriander leaves with citrusy aroma. Perfect garnish for every Indian dish.", nutrition: "Rich in Vitamin K, Vitamin A and antioxidants.", tips: "Store stems-down in a glass of water. Cover with plastic bag in fridge.", origin: "Nashik, Maharashtra", stock: 50 },
    { name: "Mint (Pudina)", price: 40, unit: "kg", category: "Vegetables", emoji: "🌿", gradient: "linear-gradient(135deg, #11998e, #38ef7d)", description: "Fresh mint leaves, cooling and aromatic. Great for chutney, raita, drinks and biryani.", nutrition: "Rich in Vitamin A, Vitamin C and antioxidants. Aids digestion.", tips: "Store stems-down in water in fridge. Can also be dried for later use.", origin: "Nagpur, Maharashtra", stock: 50 },
    { name: "Lemon", price: 80, unit: "kg", category: "Vegetables", emoji: "🍋", gradient: "linear-gradient(135deg, #fff44f, #ffd700)", description: "Fresh juicy lemons, perfect for lemonade, cooking, dressings and garnishing.", nutrition: "Excellent source of Vitamin C. Aids in digestion and immunity.", tips: "Store at room temperature for a week or refrigerate for up to a month.", origin: "Nagpur, Maharashtra", stock: 100 },
    { name: "Mushroom", price: 50, unit: "pack", category: "Vegetables", emoji: "🍄", gradient: "linear-gradient(135deg, #d4a574, #8b7355)", description: "Fresh button mushrooms, rich in umami flavor. Perfect for curry, stir-fry and soup.", nutrition: "Low in calories. Rich in Protein, B Vitamins, Selenium and antioxidants.", tips: "Store in paper bag in refrigerator. Do not wash until ready to use.", origin: "Himachal Pradesh", stock: 20 },
    { name: "Sweet Corn", price: 30, unit: "kg", category: "Vegetables", emoji: "🌽", gradient: "linear-gradient(135deg, #ffd700, #ff9a44)", description: "Sweet and juicy corn on the cob. Great for boiling, grilling, soup and chaat.", nutrition: "Rich in Fiber, Vitamin B, antioxidants and essential minerals.", tips: "Refrigerate immediately. Best consumed within 1-2 days for sweetness.", origin: "Karnataka", stock: 40 },
    { name: "Broccoli", price: 120, unit: "kg", category: "Vegetables", emoji: "🥦", gradient: "linear-gradient(135deg, #2d8f2d, #56ab2f)", description: "Fresh green broccoli florets, a superfood. Great for stir-fry, pasta and healthy eating.", nutrition: "High in Vitamin C, Vitamin K, Fiber and Sulforaphane (anti-cancer).", tips: "Store in refrigerator crisper. Do not wash until ready to use.", origin: "Ooty, Tamil Nadu", stock: 20 },
    { name: "Pumpkin (Kaddu)", price: 30, unit: "kg", category: "Vegetables", emoji: "🎃", gradient: "linear-gradient(135deg, #ff9a44, #ff6b6b)", description: "Fresh sweet pumpkin, perfect for kaddu sabzi, pie, soup and curries.", nutrition: "Low in calories. Rich in Vitamin A, Vitamin C, Potassium and Fiber.", tips: "Whole pumpkin can last weeks at room temperature. Refrigerate cut pieces.", origin: "Rajasthan", stock: 20 },
    { name: "Curry Leaves", price: 25, unit: "bunch", category: "Vegetables", emoji: "🌿", gradient: "linear-gradient(135deg, #2d8f2d, #11998e)", description: "Fresh curry leaves with authentic South Indian aroma. Essential for tempering.", nutrition: "Rich in Iron, Calcium, Vitamin A and antioxidants.", tips: "Store in refrigerator wrapped in paper. Can be dried or frozen for longer use.", origin: "Chennai, Tamil Nadu", stock: 50 },

    // FRUITS
    { name: "Apple", price: 150, unit: "kg", category: "Fruits", emoji: "🍎", gradient: "linear-gradient(135deg, #ff6b6b, #ee5a24)", description: "Crisp and juicy apples, the king of fruits. Perfect for snacking, juice and desserts.", nutrition: "Rich in Fiber, Vitamin C and antioxidants. Aids heart health and digestion.", tips: "Store in refrigerator to keep crisp. Keep away from other fruits (releases ethylene).", origin: "Shimla, Himachal Pradesh", stock: 40 },
    { name: "Banana", price: 50, unit: "dozen", category: "Fruits", emoji: "🍌", gradient: "linear-gradient(135deg, #ffd700, #ff9a44)", description: "Fresh ripe bananas, energy-packed snack. Great for smoothies, desserts and baking.", nutrition: "Rich in Potassium, Vitamin B6, Vitamin C and Fiber.", tips: "Store at room temperature. Separate from bunch to slow ripening. Refrigerate to stop ripening.", origin: "Jalgaon, Maharashtra", stock: 60 },
    { name: "Orange", price: 80, unit: "kg", category: "Fruits", emoji: "🍊", gradient: "linear-gradient(135deg, #ff9a44, #ff6b6b)", description: "Sweet and tangy oranges, loaded with Vitamin C. Perfect for juicing and snacking.", nutrition: "Excellent source of Vitamin C, Thiamine, Folate and antioxidants.", tips: "Store at room temperature or refrigerate for up to 2 weeks. Squeeze fresh for best taste.", origin: "Nagpur, Maharashtra", stock: 40 },
    { name: "Mango", price: 120, unit: "kg", category: "Fruits", emoji: "🥭", gradient: "linear-gradient(135deg, #ffd700, #ff9a44)", description: "The king of fruits! Sweet, pulpy Alphonso mangoes. Perfect for dessert, shake and aamras.", nutrition: "Rich in Vitamin C, Vitamin A, Folate and antioxidants.", tips: "Ripen at room temperature. Refrigerate ripe mangoes for up to a week.", origin: "Ratnagiri, Maharashtra", stock: 30 },
    { name: "Grapes", price: 100, unit: "kg", category: "Fruits", emoji: "🍇", gradient: "linear-gradient(135deg, #7b4397, #dc2430)", description: "Fresh seedless grapes, sweet and juicy. Perfect for snacking, juice and fruit salads.", nutrition: "Rich in Vitamin C, Vitamin K and antioxidants like Resveratrol.", tips: "Wash before eating. Store in refrigerator in perforated bag for up to a week.", origin: "Nashik, Maharashtra", stock: 35 },
    { name: "Watermelon", price: 80, unit: "kg", category: "Fruits", emoji: "🍉", gradient: "linear-gradient(135deg, #ff6b6b, #ee5a24)", description: "Refreshing summer watermelon, hydrating and sweet. Perfect for juice and fruit chaat.", nutrition: "92% water content. Rich in Lycopene, Vitamin A and Vitamin C.", tips: "Store whole at room temperature. Refrigerate cut pieces wrapped in plastic.", origin: "Kurnool, Andhra Pradesh", stock: 20 },
    { name: "Papaya", price: 40, unit: "kg", category: "Fruits", emoji: "🍈", gradient: "linear-gradient(135deg, #ff9a44, #ffcc02)", description: "Ripe sweet papaya with soft flesh. Great for breakfast, smoothies and digestive health.", nutrition: "Rich in Vitamin C, Vitamin A, Folate and the enzyme Papain.", tips: "Ripen at room temperature. Refrigerate ripe papaya for 3-4 days.", origin: "Thiruvananthapuram, Kerala", stock: 20 },
    { name: "Pomegranate (Anar)", price: 150, unit: "kg", category: "Fruits", emoji: "🫐", gradient: "linear-gradient(135deg, #dc143c, #8b0000)", description: "Fresh ruby-red pomegranate seeds, sweet and tangy. Perfect for salads, juice and snacking.", nutrition: "Rich in antioxidants, Vitamin C, Vitamin K and Potassium.", tips: "Store in refrigerator for up to 2 months. Extract seeds and refrigerate in airtight container.", origin: "Nashik, Maharashtra", stock: 30 },
    { name: "Guava (Amrood)", price: 50, unit: "kg", category: "Fruits", emoji: "🍐", gradient: "linear-gradient(135deg, #56ab2f, #a8e063)", description: "Fresh fragrant guava, loaded with Vitamin C. Great for eating raw, juice and chaat.", nutrition: "Highest Vitamin C content among fruits. Rich in Fiber and antioxidants.", tips: "Store at room temperature until ripe. Refrigerate for up to a week.", origin: "Allahabad, UP", stock: 40 },
    { name: "Kiwi", price: 30, unit: "piece", category: "Fruits", emoji: "🥝", gradient: "linear-gradient(135deg, #56ab2f, #2d8f2d)", description: "Exotic green kiwi with sweet-tart flavor. Rich in Vitamin C and great for fruit bowls.", nutrition: "Very high in Vitamin C, Vitamin K, Fiber and antioxidants.", tips: "Ripen at room temperature. Refrigerate ripe kiwis for up to a month.", origin: "Imported / Himachal Pradesh", stock: 30 },
    { name: "Pineapple", price: 50, unit: "kg", category: "Fruits", emoji: "🍍", gradient: "linear-gradient(135deg, #ffd700, #56ab2f)", description: "Sweet tropical pineapple with juicy flesh. Great for juice, dessert and fruit salad.", nutrition: "Rich in Vitamin C, Manganese and the enzyme Bromelain.", tips: "Ripen at room temperature. Refrigerate cut pieces. Keep upside down before cutting.", origin: "Kerala", stock: 20 },
    { name: "Strawberry", price: 80, unit: "box", category: "Fruits", emoji: "🍓", gradient: "linear-gradient(135deg, #ff6b6b, #dc143c)", description: "Fresh red strawberries, sweet and fragrant. Perfect for desserts, smoothies and snacks.", nutrition: "Rich in Vitamin C, Manganese and antioxidants.", tips: "Do not wash until ready to eat. Refrigerate in a single layer on paper towel.", origin: "Mahabaleshwar, Maharashtra", stock: 25 },
    { name: "Cherry", price: 500, unit: "kg", category: "Fruits", emoji: "🍒", gradient: "linear-gradient(135deg, #8b0000, #dc143c)", description: "Premium sweet cherries, juicy and delicious. Perfect for snacking, baking and desserts.", nutrition: "Rich in Vitamin C, Potassium and antioxidants. Anti-inflammatory.", tips: "Refrigerate unwashed in airtight container. Wash just before eating.", origin: "Imported / Kashmir", stock: 10 },
    { name: "Litchi", price: 125, unit: "kg", category: "Fruits", emoji: "🫐", gradient: "linear-gradient(135deg, #ff6b6b, #ffcc02)", description: "Sweet and fragrant litchi with translucent flesh. A refreshing summer fruit.", nutrition: "Rich in Vitamin C, Potassium, Copper and antioxidants.", tips: "Refrigerate immediately. Peel and deseed before eating. Best consumed fresh.", origin: "Bihar / Kashmir", stock: 15 },
    { name: "Peach (Aadoo)", price: 125, unit: "kg", category: "Fruits", emoji: "🍑", gradient: "linear-gradient(135deg, #ffb6c1, #ff9a44)", description: "Soft and juicy peaches with fuzzy skin. Great for eating fresh, jams and desserts.", nutrition: "Rich in Vitamin C, Vitamin A, Fiber and Potassium.", tips: "Ripen at room temperature. Refrigerate ripe peaches for 3-5 days.", origin: "Himachal Pradesh", stock: 20 },
    { name: "Plum (Alu Bukhara)", price: 125, unit: "kg", category: "Fruits", emoji: "🟣", gradient: "linear-gradient(135deg, #7b4397, #4a1a6b)", description: "Sweet and tart plums with vibrant color. Perfect for snacking, baking and preserves.", nutrition: "Rich in Vitamin C, Vitamin K, Fiber and antioxidants.", tips: "Ripen at room temperature. Refrigerate ripe plums for up to 5 days.", origin: "Himachal Pradesh", stock: 20 },
    { name: "Fig (Anjeer)", price: 400, unit: "kg", category: "Fruits", emoji: "🟤", gradient: "linear-gradient(135deg, #8b7355, #5c4033)", description: "Sweet and chewy figs, rich in natural sugars. Great for desserts, snacks and health.", nutrition: "High in Fiber, Calcium, Potassium and antioxidants.", tips: "Fresh figs should be consumed quickly. Dried figs can be stored for months.", origin: "Turkey / Pune", stock: 15 },
    { name: "Coconut", price: 35, unit: "piece", category: "Fruits", emoji: "🥥", gradient: "linear-gradient(135deg, #8b7355, #d4a574)", description: "Fresh coconut with sweet water and tender meat. Essential for cooking and religious use.", nutrition: "Rich in healthy fats, Fiber, Manganese and Copper.", tips: "Store at room temperature for a few days. Refrigerate for up to a week.", origin: "Kerala", stock: 40 },
    { name: "Dragon Fruit", price: 400, unit: "kg", category: "Fruits", emoji: "🐉", gradient: "linear-gradient(135deg, #ff6b6b, #7b4397)", description: "Exotic dragon fruit with mild sweet flavor and stunning appearance. Great for smoothie bowls.", nutrition: "Low in calories. Rich in Vitamin C, Fiber and Magnesium.", tips: "Refrigerate whole for up to 5 days. Cut just before eating.", origin: "Vietnam / Maharashtra", stock: 15 },
    { name: "Avocado", price: 80, unit: "piece", category: "Fruits", emoji: "🥑", gradient: "linear-gradient(135deg, #56ab2f, #2d8f2d)", description: "Creamy and nutritious avocado, perfect for toast, smoothies, guacamole and salads.", nutrition: "Rich in healthy monounsaturated fats, Potassium, Fiber and Vitamin E.", tips: "Ripen at room temperature. Refrigerate ripe avocados. Add lemon juice to cut halves.", origin: "Imported / Maharashtra", stock: 15 },

    // GROCERY
    { name: "Rice", price: 80, unit: "kg", category: "Grocery", emoji: "🍚", gradient: "linear-gradient(135deg, #f5f5dc, #d4a574)", description: "Premium quality basmati rice, long grain and aromatic. Perfect for biryani, pulao and daily meals.", nutrition: "Rich in Carbohydrates and energy. Low in fat and sodium.", tips: "Store in airtight container in cool, dry place. Keep bay leaves to repel insects.", origin: "Punjab / Haryana", stock: 80 },
    { name: "Milk", price: 70, unit: "litre", category: "Grocery", emoji: "🥛", gradient: "linear-gradient(135deg, #f5f5f5, #e0e0e0)", description: "Fresh full-cream milk, pasteurized and pure. Great for tea, coffee, paneer and desserts.", nutrition: "Excellent source of Calcium, Protein, Vitamin D and Vitamin B12.", tips: "Refrigerate immediately. Boil before consumption. Use within the expiry date.", origin: "Amul / Local Dairy", stock: 100 },
    { name: "Wheat Atta", price: 40, unit: "kg", category: "Grocery", emoji: "🌾", gradient: "linear-gradient(135deg, #d4a574, #c0956c)", description: "Fresh stone-ground wheat flour, soft and nutritious. Perfect for roti, chapati and paratha.", nutrition: "Rich in Fiber, Protein, Iron and B Vitamins.", tips: "Store in airtight container in cool, dry place. Refrigerate in humid climates.", origin: "MP / Rajasthan", stock: 70 },
    { name: "Toor Dal", price: 110, unit: "kg", category: "Grocery", emoji: "🫘", gradient: "linear-gradient(135deg, #ffd700, #ff9a44)", description: "Premium quality toor dal, cooks soft and creamy. Essential for dal tadka and sambar.", nutrition: "High in Protein, Fiber, Folate and Iron.", tips: "Store in airtight container. Wash thoroughly before cooking. Soak for faster cooking.", origin: "Gujarat / Maharashtra", stock: 60 },
    { name: "Sugar", price: 70, unit: "kg", category: "Grocery", emoji: "🧂", gradient: "linear-gradient(135deg, #f5f5f5, #e0e0e0)", description: "Fine granulated white sugar, pure and sweet. Essential for tea, coffee, baking and desserts.", nutrition: "Quick source of energy. Use in moderation.", tips: "Store in airtight container in dry place. Keep away from moisture to prevent clumping.", origin: "UP / Maharashtra", stock: 80 },
    { name: "Salt", price: 45, unit: "kg", category: "Grocery", emoji: "🧂", gradient: "linear-gradient(135deg, #f5f5f5, #bdc3c7)", description: "Iodized table salt, essential for cooking and seasoning. Keeps thyroid healthy.", nutrition: "Source of Iodine and Sodium. Essential for body functions in small amounts.", tips: "Store in dry, airtight container. Keep salt shaker away from steam.", origin: "Gujarat (Rock Salt)", stock: 90 },
    { name: "Cooking Oil", price: 250, unit: "litre", category: "Grocery", emoji: "🫗", gradient: "linear-gradient(135deg, #ffd700, #d4a574)", description: "Refined sunflower cooking oil, light and healthy. Perfect for frying, sautéing and cooking.", nutrition: "Source of Vitamin E and healthy unsaturated fats. Cholesterol-free.", tips: "Store in cool, dark place. Do not reuse oil multiple times for frying.", origin: "Fortune / Saffola", stock: 50 },
    { name: "Tea Powder", price: 400, unit: "kg", category: "Grocery", emoji: "🍵", gradient: "linear-gradient(135deg, #8b4513, #d2691e)", description: "Premium CTC tea powder, strong and flavorful. Perfect for masala chai and regular tea.", nutrition: "Contains antioxidants (Catechins). May boost metabolism and heart health.", tips: "Store in airtight container away from light and moisture. Use within 3 months.", origin: "Assam / Darjeeling", stock: 40 },
    { name: "Bread", price: 45, unit: "pack", category: "Grocery", emoji: "🍞", gradient: "linear-gradient(135deg, #d4a574, #c0956c)", description: "Fresh soft white bread, sliced and ready to eat. Perfect for sandwiches and toast.", nutrition: "Source of Carbohydrates and some B Vitamins. Best as a quick meal.", tips: "Store in bread box at room temperature. Refrigerate to prevent mold in humid weather.", origin: "English Oven / Local Bakery", stock: 40 },
    { name: "Eggs", price: 7, unit: "piece", category: "Grocery", emoji: "🥚", gradient: "linear-gradient(135deg, #f5f5dc, #d4a574)", description: "Farm-fresh chicken eggs, protein-rich and versatile. Great for breakfast, baking and cooking.", nutrition: "Excellent source of Protein, Vitamin D, B12 and Choline.", tips: "Refrigerate pointed end down. Use within 3-4 weeks. Check freshness in water test.", origin: "Local Poultry Farm", stock: 60 },
];

async function seed() {
    try {
        const URI = process.env.MONGODB_URI || "mongodb://localhost:27017/freshmart";
        await mongoose.connect(URI);
        console.log("✅ MongoDB connected");

        // Upsert products by name: never deletes existing data, never duplicates.
        // Existing product fields (stock, rating, etc.) for matching names are refreshed
        // from the catalog above without wiping the collection.
        const ops = products.map((p) => ({
            updateOne: {
                filter: { name: p.name },
                update: { $set: p },
                upsert: true
            }
        }));
        const result = await Product.bulkWrite(ops, { ordered: false });
        console.log(`✅ Synced ${products.length} catalog items → ${result.upsertedCount} created, ${result.matchedCount} already existed, ${result.modifiedCount} updated`);

        mongoose.disconnect();
        console.log("🎉 Done!");
        process.exit(0);
    } catch (error) {
        console.error("❌ Seed error:", error.message);
        process.exit(1);
    }
}

seed();
